description: "Run a custom bun command"
parameters:
  command:
    type: string
    description: "The bun command to run"
  workspace:
    type: string
    description: "The workspace/folder name to run the command in"
steps:
  - run:
      name: Run custom command
      command: bun --filter <<parameters.workspace>> <<parameters.command>>
