description: "Run a custom pnpm command"
parameters:
  command:
    type: string
    description: "The pnpm command to run"
  workspace:
    type: string
    description: "The workspace/folder name to run the command in"
steps:
  - run:
      name: Run custom command
      command: pnpm --filter <<parameters.workspace>> <<parameters.command>>
